# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/lorenzogm/ring"
          source_branch: "main"
          destination_repo: "https://github.com/lorenzogm/dindim.es"
          destination_branch: "main"
